export const UI_CONSTANTS = {
  MESSAGE_GROUP_THRESHOLD_MS: 2 * 60 * 1000, // 2 minutes
  TYPING_DEBOUNCE_MS: 2000,
  SEND_RESET_DELAY_MS: 400,
  SEARCH_DEBOUNCE_MS: 300,
  CONVERSATION_PAGE_SIZE: 50,
  VERIFY_REDIRECT_DELAY_MS: 3000,
} as const;

export type UiConstants = typeof UI_CONSTANTS;
